name: "ethereum-writer-deployer"

on:
  push:
    branches:
      - '**'
  release:
    types: [ published ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: python --version
      - run: env
      - name: Run npm ci
        run: npm ci
      - run: npm run build
      # Unit tests
      - run: npm install --no-save tap-xunit
      - run: mkdir -p _out/unit _out/e2e
      - run: npm test --  --timeout=1m
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./dist

  release-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./dist
      - name: Generate version
        run: ./create-version-file.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_STAGING_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_STAGING_PASSWORD }}
      - name: Build and push image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t orbsnetworkstaging/ethereum-writer:$(cat .version) --push .
